version: '3.8'


services:
  webapp:
    # build the image from Dockerfile
    build:
      context: "./webapp"
    ports:
      - "5000:5000"
    links:
      - "mongodb"
  mongodb:
    build:
      context: "./mongodb"